/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaexperto;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import sistemaexperto.Entidad.Tupla;
import sistemaexperto.negocio.NTupla;
import sistemaexperto.util.GV;
import sistemaexperto.util.listenerVariable;

/**
 *
 * @author Lion
 */
public class JPVariables extends javax.swing.JPanel{

    public JPVariables() {
        initComponents();
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLNombre = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLvalor = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jRBnumerica = new javax.swing.JRadioButton();
        jRBescalar = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jBeliminar = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTFnombre = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTFvalor = new javax.swing.JTextField();

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLNombre.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(jLNombre);

        jPanel1.add(jScrollPane3);

        jLvalor.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jScrollPane4.setViewportView(jLvalor);

        jPanel1.add(jScrollPane4);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel1.setText("Nombre Variables");
        jPanel2.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel2.setText("Valor");
        jPanel2.add(jLabel2);

        jPanel3.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel4.setText("Tipo");
        jPanel8.add(jLabel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jRBnumerica.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jRBnumerica.setText("Numerica");
        jPanel5.add(jRBnumerica, java.awt.BorderLayout.CENTER);

        jRBescalar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jRBescalar.setText("Escalar");
        jPanel5.add(jRBescalar, java.awt.BorderLayout.PAGE_START);

        jPanel8.add(jPanel5);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jBeliminar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jBeliminar.setText("Eliminar");
        jPanel4.add(jBeliminar, java.awt.BorderLayout.CENTER);

        jBguardar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jBguardar.setText("Guardar");
        jPanel4.add(jBguardar, java.awt.BorderLayout.PAGE_START);

        jPanel8.add(jPanel4);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel11.setLayout(new java.awt.GridLayout(2, 1));

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel10.add(jLabel3);

        jTFnombre.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jTFnombre.setEnabled(false);
        jPanel10.add(jTFnombre);

        jPanel11.add(jPanel10);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        jLabel5.setText("Valor");
        jLabel5.setMaximumSize(new java.awt.Dimension(43, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(43, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(43, 14));
        jPanel6.add(jLabel5);

        jTFvalor.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jTFvalor.setEnabled(false);
        jPanel6.add(jTFvalor);

        jPanel11.add(jPanel6);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBeliminar;
    public javax.swing.JButton jBguardar;
    public javax.swing.JList jLNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JList jLvalor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JRadioButton jRBescalar;
    public javax.swing.JRadioButton jRBnumerica;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTextField jTFnombre;
    public javax.swing.JTextField jTFvalor;
    // End of variables declaration//GEN-END:variables

}
